### ISSUE TITLE
https://apache.github.io/couchdb-helm is not there

### ISSUE THREAD

**Issue by blsaws** [apache/couchdb-helm#12]
Returns a 404: https://apache.github.io/couchdb-helm

We are using couchdb in the LF Acumos project, and we depend upon the couchdb helm chart (was using the one in https://github.com/helm/charts/tree/master/stable/couchdb, which has been 
deprecated). I need to have a reliable helm chart repo I can refer to. As fallback I can clone this repo but I do not have the BW really to maintain my own version of this chart (though there are issues that might force that, nonetheless)... so I will appreciate a working link to a supported replacement for the "official" helm chart in a helm repo, ASAP

**Comment by willholley** [comment]
@blsaws https://apache.github.io/couchdb-helm returns a 404 because there is no `index.html`; I think we should add one so that the site doesn't look inactive when viewed with a web browser.

Despite this issue, the site does host the helm chart repository. If you follow the instructions at https://hub.helm.sh/charts/couchdb/couchdb to add it as a helm repo, you should be good.

**Comment by blsaws** [comment]
OK, thanks. I didn't see those instructions first. I can deploy it now, but I have issues (same as I had with the "official" chart). Is there a particular forum other than here where technical issues with the chart should be reported?

**Comment by blsaws** [comment]
Closed as the docs clarify how to install the chart.

**Comment by willholley** [comment]
@blsaws please report any problems as issues in this repository. This is the new home of the "official" chart - the maintainers have not changed.
