### ISSUE TITLE
Add Jenkins integration

### ISSUE THREAD

**Issue by willholley** [apache/couchdb-helm#3]
#1 adds chart testing using [KinD](https://github.com/kubernetes-sigs/kind). It should be possible to run these as a CI check in Jenkins, assuming we can get this repository hooked up.

Is there more to it than just adding a Jenkinsfile?

**Comment by wohali** [comment]
@willholley You'll need to create a new CouchDB Jenkins job in the CouchDB folder over at builds.apache.org. You can copy the current setup for mine if you like, though you may want to add a new set of credentials so GH doesn't throttle because of excessive API endpoint usage.

You'll need to get access to add new jobs there, which I believe requires @janl to approve a request you make through ASF Infra JIRA.

**Comment by willholley** [comment]
@janl are you able to grant me access to CouchDB build jobs in Jenkins? The infra [wiki](https://cwiki.apache.org/confluence/display/INFRA/Jenkins#Jenkins-HowdoIgetanaccount) and [recent Jira tickets](https://issues.apache.org/jira/browse/INFRA-18054) suggest this may be self-service for PMC chairs by adding me to the hudson-jobadmin group in LDAP using [whimsy](https://whimsy.apache.org/roster/group/hudson-jobadmin). 

If not, I'll open an infra ticket as @wohali suggested.

**Comment by willholley** [comment]
replaced by #80
