### ISSUE TITLE
RFC: Is this project still maintained? Fork needed?

### ISSUE THREAD

**Issue by Nold360** [apache/couchdb-helm#53]
**Describe the bug**
This repos `main` branch hasn't been updated for 8 month as I'm writing this issue. 

Basic features like the cluster setup & couchdb 3 are still not available/merged or [in case of CDB3] even been worked on publicly.

**What you expected to happen**:

I would love to see this repo getting active maintenance as we currently started using CouchDB in production. But if Apache doesn't care about it, the community or I might have to fork the project and maintain it as a community project.

**Comment by rnewson** [comment]
This _is_ a community project, it only awaits contributions from the community. Go right ahead. :)

**Comment by kocolosk** [comment]
Hi, a couple of comments on the specific issues you mentioned:

- CouchDB 3.1 was added in #36 but we inadvertently merged it into the wrong branch in the `master` -> `main` cutover. That's an oversight, anyone would be welcome to submit a PR to get it merged to the correct branch (and bump to 3.1.1). It's nothing subtle, just bumping default versions and running the YAML generation machinery. The chart itself "just works" with 3.x.
- "Cluster Setup" is a good discussion topic, some of the work that it does is redundant because the chart knows how to join nodes into a cluster automatically using the `seedlist` functionality. My general thought is that if there are k8s-centric ways to implement the things that "cluster setup" does then we should consider them.

I'd also point out that a lot of the energy for automating the management of CouchDB in Kubernetes is being directed to the [CouchDB Operator](https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-apache-couchdb-overview#apache-couchdb-operator-overview). If you haven't seen that, maybe check to see if the extra functionality it provides is a good fit. I know the IBM folks provide commercial support for it as well if needed.

Echoing what Bob said, if you're inclined to spend some cycles on the Helm chart, there shouldn't be any need to fork it. We'd be happy to have the extra input on this project!

**Comment by kocolosk** [comment]
Ah I see that @flimzy also already picked up the cluster setup integration in #42

**Comment by Nold360** [comment]
Thanks for letting me know @kocolosk when time comes I'll eventually start contributing :)
